### ISSUE TITLE
Easiest way to fill the app with some data

### ISSUE THREAD

**Issue by egabor** [google/iosched-ios#1]
The schedule screen is completely empty after logging in. Some instructions and example data would be great that describes what to upload in which structure to Firestore.

**Comment by morganchen12** [comment]
@egabor unfortunately there's no simple way to fill the app with data currently. In the future we can look at adding a data generation script to populate your Firestore database with schedule info. However, even after populating the database, note that features like reservations still won't work because the proper Cloud Functions won't be set up on your project.

The functions have not been open-sourced this year, but we can look at doing that next year.

**Comment by legalimpurity** [comment]
Hi @morganchen12 ,

Why dont we use the same firebase project that we are using in the android github sample. I had a look at the project and tried to imitate the settings. But was unsuccessful.

You can check out its json here.
https://github.com/google/iosched/blob/master/mobile/google-services.json
I am also making a PR with very small changes required in the code for the code to work. But, not having the plist file is the biggest problem as of now to explore this project further.

Thanks,
legalimpurity

**Comment by morganchen12** [comment]
Sounds good @legalimpurity, I'll get around to this soon.

**Comment by morganchen12** [comment]
Added the default configuration files. These point to the same environment as the Android app.

Sorry for the delay.
